### ISSUE TITLE
Error code: 127

### ISSUE THREAD

**Issue by syunkevichdemandbase** [danielkaiser/python-chromedriver-binary#11]
Hi @danielkaiser 

Any thoughts on how this can be fixed?
```
"errorMessage": "Message: Service chromedriver unexpectedly exited. Status code was: 127\n",
    "errorType": "WebDriverException",
    "stackTrace": [
      "  File \"/var/task/get_creative_size.py\", line 76, in lambda_handler\n    driver = __chrome_driver()\n",
      "  File \"/var/task/get_creative_size.py\", line 66, in __chrome_driver\n    driver = webdriver.Chrome()\n",
      "  File \"/var/task/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n",
      "  File \"/var/task/selenium/webdriver/common/service.py\", line 98, in start\n    self.assert_process_still_running()\n",
      "  File \"/var/task/selenium/webdriver/common/service.py\", line 109, in assert_process_still_running\n    raise WebDriverException(\n"
    ]
```

**Comment by danielkaiser** [comment]
Hi @syunkevichdemandbase 

from the given error message it's really hard to tell what exactly went wrong. First of all, could you please check if your chromedriver-binary version (or chromedriver version) matches the version of your chrome/chromium installation? It is quite sensitive to differences in versions.

Also if you are running your code in docker (for example in CI/CD pipelines) there is often only limited space in `/dev/shm` which can result in chrome crashing. To avoid this you could try adding the `--disable-dev-shm-usage` option:

```Python
import chromedriver_binary
from selenium import webdriver

options = webdriver.chrome.options.Options()
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(options=options)
driver.get("http://www.python.org")
```

I hope this helps investigating the problem.

**Comment by danielkaiser** [comment]
As there was no repsonse over a longer period of time I'm assuming this issue is resolved. 
If the problem persists feel free to reopen this issue.
