### ISSUE TITLE
Failed to download chromedriver archive

### ISSUE THREAD

**Issue by roshinv** [danielkaiser/python-chromedriver-binary#12]
I keep getting this error:
RuntimeError: Failed to download chromedriver archive: https://chromedriver.storage.googleapis.com/81.0.4044.20/chromedriver_linux64.zip

command used:
pip install chromedriver-binary

**Comment by danielkaiser** [comment]
Hi @roshinv 
can you download the file if you open the printed URL in your browser? What operating system so you use and which version of python interpreter do you use?

**Comment by marco2012** [comment]
Fixed on MacOS Catalina installing Python SSL certificates as explained in this post https://stackoverflow.com/a/42107877

**Comment by danielkaiser** [comment]
Thanks @marco2012 for the hint. As there was no further response from @roshinv over a longer period of time I'm assuming this issue is resolved.
If the problem persists feel free to reopen this issue.
