### ISSUE TITLE
Webdriver exception.

### ISSUE THREAD

**Issue by nonoumasy** [danielkaiser/python-chromedriver-binary#13]
OS: Mac
Chrome: 81.0
Google Colab

I am getting this error:
`---------------------------------------------------------------------------
WebDriverException                        Traceback (most recent call last)
<ipython-input-34-e9ffeba4df5d> in <module>()
      3 import pandas as pd
      4 
----> 5 driver = webdriver.Chrome()
      6 driver.get('https://www.doh.wa.gov/Emergencies/Coronavirus')
      7 

2 frames
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py in assert_process_still_running(self)
    109             raise WebDriverException(
    110                 'Service %s unexpectedly exited. Status code was: %s'
--> 111                 % (self.path, return_code)
    112             )
    113 

WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: -6`

This is my code:
`
!pip install selenium chromedriver-binary

from selenium import webdriver
import chromedriver_binary 
import pandas as pd

driver = webdriver.Chrome()
driver.get('https://www.doh.wa.gov/Emergencies/Coronavirus')

html = driver.page_source
pd.read_html(html)
`

**Comment by danielkaiser** [comment]
Hi!

As you are using Chrome version 81.0 you will need a matching chromedriver binary version. Please
```
pip install chromedriver-binary==81.0.4044.69.0
```
and then try your code again.

**Comment by danielkaiser** [comment]
As there was no repsonse over a longer period of time I'm assuming this issue is resolved. 
If the problem persists feel free to reopen this issue.
