### ISSUE TITLE
Session not created error

### ISSUE THREAD

**Issue by Quessts** [danielkaiser/python-chromedriver-binary#14]
Tried running it. Got this error
'''
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 85
'''

**Comment by danielkaiser** [comment]
Hi,

as the error message suggests: please make sure to use a
chromedriver-binary version suitable for your Chrome version. If you have
Chrome 84.x installed you can install the package with

pip install chromedriver-binary==84




Quessts <notifications@github.com> schrieb am Fr., 21. Aug. 2020, 18:26:

**Comment by danielkaiser** [comment]
As there was no repsonse over a longer period of time I'm assuming this issue is resolved. 
If the problem persists feel free to reopen this issue.
