### ISSUE TITLE
Clarify package usage: do I need google-chrome installed before using?

### ISSUE THREAD

**Issue by AIGeneratedUsername** [danielkaiser/python-chromedriver-binary#15]
**My issue.**

I have the following error produced by the [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager/issues/73) bug.

`ValueError: Could not get version for Chrome with this command: google-chrome --version || google-chrome-stable --version`

**What I tried.**

1. `pip install chromedriver-binary`
2.  Add `import chromedriver_binary` into my code.

I still have the same issue. Steps above changed nothing.

**Question.**

Do I need to install a Chrome browser manually before using your library?

**Comment by danielkaiser** [comment]
Hi @AIGeneratedUsername,

yes you need to install a Chrome or Chromium browser before you can use this package (if you want the required ChromeDriver version to be [automatically detected](https://github.com/danielkaiser/python-chromedriver-binary#automatically-detected-versions) chrome/chromium even needs to be available before package installation).

This package only installs the [ChromeDriver](https://chromedriver.chromium.org/) which implements a WebDriver server to control the browser for automated testing. The actual browser therefore needs to be installed on the system from a different source.
