### ISSUE TITLE
Chromedriver version 100

### ISSUE THREAD

**Issue by Keeds23** [danielkaiser/python-chromedriver-binary#19]
This version of ChromeDriver only supports Chrome version 100
Current browser version is 99.0.4844.83 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

The latest version is still 99 so how do I get it to use the previous chromedriver?

**Comment by danielkaiser** [comment]
Hi,

you can install the `chromedriver-binary-auto` package instead the latest `chromedriver-binary` package to get the ChromeDriver version matching your browser. See [this section of the readme](https://github.com/danielkaiser/python-chromedriver-binary#automatically-detected-versions) and the comments in issue #10 for more details.

**Comment by danielkaiser** [comment]
Hi, as there is no feedback on my suggested fix over a long time I am going to close this issue.
If the issue persists for you, please check the `chromedriver-binary-auto` package before re-opening this issue.
