### ISSUE TITLE
Chromedriver version 101

### ISSUE THREAD

**Issue by alanponce** [danielkaiser/python-chromedriver-binary#20]
Hi, same issue here

SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 100.0.4896.88 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome.

Session Information
chromedriver_binary NA
ipykernel           6.9.1
numpy               1.21.5
pandas              1.4.1
session_info        1.0.0
-----
Click to view modules imported as dependencies
-----
IPython             8.2.0
jupyter_client      6.1.12
jupyter_core        4.9.2
jupyterlab          3.3.2
notebook            6.4.8
-----
Python 3.9.12 (main, Apr  5 2022, 01:53:17) [Clang 12.0.0 ]
macOS-10.13.6-x86_64-i386-64bit
-----
Session information updated at 2022-04-13 20:16

**Comment by danielkaiser** [comment]
Hi, 

please see Issue #19. 
Either specify the desired version during installation, e.g. `pip install chromedriver-binary~=100.0` or simply use the "auto" version of the package: `pip install chromedriver-binary-auto`.

**Comment by danielkaiser** [comment]
Hi, as there is no feedback on my suggested fix over a long time I am going to close this issue.
If the issue persists for you, please check the `chromedriver-binary-auto` package before re-opening this issue.

**Comment by alanponce** [comment]
Hi,

Sorry for my delay answering your comments. It works and I really appreciate your help
