### ISSUE TITLE
Chromedriver-auto installs v97 instead of latest

### ISSUE THREAD

**Issue by Zeroxk** [danielkaiser/python-chromedriver-binary#22]
Python version 3.9.0
chromedriver-binary-auto v0.1.1
Windows 10

When running `pip install chromedriver-binary-auto` when I check inside the `chromedriver-binary` site-package the `chromedriver.exe` is v97 instead of latest (as of today v100)

**Comment by Zeroxk** [comment]
I found the issue, my pip cache had an old version. Purging cache fixed it

**Comment by danielkaiser** [comment]
Thanks for reporting this issue and the solution. I added a note about this at the end of the [installation section of the readme](https://github.com/danielkaiser/python-chromedriver-binary#automatically-detected-versions).
