### ISSUE TITLE
Download chrome driver getting failed

### ISSUE THREAD

**Issue by Ajithkumaremis** [danielkaiser/python-chromedriver-binary#27]
The download of ChromeDriver is failing due to recent changes in the ChromeDriver migration sites. Consequently, downloading the latest version is not possible. The attempt to download the chromedriver archive from https://chromedriver.storage.googleapis.com/114.0.5735.133/chromedriver_linux64.zip has also failed. For more information, you can visit https://sites.google.com/corp/chromium.org/driver/. Please share any workarounds or quick fixes if available.

**Comment by danielkaiser** [comment]
Hi @Ajithkumaremis,

as mentioned in #26 there is no Chromedriver release available for Chrome 114.0.5735, neither at the new location nor the old.

**Comment by danielkaiser** [comment]
I just noticed that there was a typo in `chromedriver-binary-auto` causing it to use the new behavior starting with Chrome v113 instead of 115. If you encountered the problem with the `-auto` package you might want to try `chromedriver-binary-auto==0.3.1` where this issue is fixed.

**Comment by Ajithkumaremis** [comment]
Hi @danielkaiser ,
        Thanks for the quick response. I will check with this chromedriver-binary-auto==0.3.1. 
Regards,
Ajith
