### ISSUE TITLE
cannot find Chrome binary

### ISSUE THREAD

**Issue by rubenflamshepherd** [danielkaiser/python-chromedriver-binary#3]
Hey,

So I can get this running on Windows 10 no problem but when I try on do the same on Linux I get the following error:

```
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from selenium import webdriver
>>> import chromedriver_binary
>>> driver = webdriver.Chrome()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
```

Any light you could shed on the matter would be very much appreciated!

**Comment by danielkaiser** [comment]
Hello,

from the error message I would say the chromedriver binary is installed correctly and was found in `$PATH` and is the latest version (2.41). 
But it seems as if it can't find a chrome binary. Do you have chrome or chromium installed? I use chromium on my machine (debian buster, chromium 68.0.3440) installed via `apt install chromium` and I can start the selenium webdriver without any problems. 
If you have installed chrome or chomium yourself without using a package manager like apt/yum/dnf please make sure that your chrome binary version is compatible with the chromedriver binary version and either upgrade the browser or downgrade the Python package (compatibility information can be found here: http://chromedriver.chromium.org/downloads).

Please let me know if that helped

**Comment by rubenflamshepherd** [comment]
Hey, just an update, didn't want to go radio silent on you. I do not have chrome, so I'll be installing it using our package manager (though I was trying to point to a local version of chrome, and not a system-wide install). I'll be getting to this/further updating you tomorrow when I have access to the affected systems.

**Comment by danielkaiser** [comment]
Hello,
you can use your locally installed version as well.
The problem is that the chromedriver does not search the `PATH` environment but only the default chrome installation paths. But you can explicitly pass a chrome/chromium binary to be used:
```Python
from selenium import webdriver
import chromedriver_binary
driver = webdriver.Chrome("/path/to/chrome")
```
Note that you have to pass the complete filename of your chrome/chromium binary and not just its containig folder (like you would do in the `PATH` variable).

**Comment by rubenflamshepherd** [comment]
So I downloaded chromium using yum as per https://www.hiroom2.com/2017/08/11/centos-7-chromium-en/ and this seems to work. I'll look into running this through a local version of chrome separately. Thanks for you timely assistance Daniel!
