### ISSUE TITLE
Specify version on install

### ISSUE THREAD

**Issue by misantroop** [danielkaiser/python-chromedriver-binary#7]
Sometimes the specific Chrome versions can be difficult to find. Any way to specify what chromedriver to use as a parameter?

**Comment by danielkaiser** [comment]
You can control the chromedriver binary version that is installed by specifying the version of this package, for example by running
```
pip install chromedriver-binary==73.0.3683.20.0
```
you will get version `73.0.3683.20` (the last `.0` is the version of this python package for the particular chromedriver binary release).

The list of releases can be found [here](https://pypi.org/project/chromedriver-binary/#history) and should contain all [chromedriver versions](http://chromedriver.chromium.org/downloads).

**Comment by danielkaiser** [comment]
Is it okay for you if I close this issue, or do you need a different way to specify the installed version?
