### ISSUE TITLE
Doesn't update driver in path

### ISSUE THREAD

**Issue by GamingBud** [danielkaiser/python-chromedriver-binary#8]
I have a file named "chromedriver.exe" in the path of my script. I installed chromedriver-binary via pip, but it doesn't seem to work upon import.

I would like my script to update the driver each time it runs. The driver is currently at version 73, but Selenium complains because my browser it at version 74. Theoretically, the driver should have been updated to the most recent version before Selenium started working.

**Comment by danielkaiser** [comment]
I am not quite sure what you mean by 'a file named "chromedriver.exe" in the path'. 

If it is a different version of the binary you downloaded with this package automatically it should update as soon as you update the package. For example in your case you would do something like
```
pip install "chromedriver-binary>=74.0"
```
An automagic update of the binary on start is not intended, as discussed in #5.

If you have an pip updated the package and no new binary was downloaded, this is probably closely related to #9 and should be fixed soon.

**Comment by GamingBud** [comment]
Ah, alright. I misunderstood the documentation then. Sorry about that.
